---
- hosts: '{{ host }}'
  connection: local

  tasks:
    - name: Add A01-MM2PE-WEB01
      tower_host:
        name: A01-MM2PE-WEB01
        inventory: "AWS"
        state: present
        tower_username: "admin"
        tower_password: "admin"
        tower_host: "https://192.168.1.235"
        validate_certs: no
        variables:
          name: "A01-MM2PE-WEB01"

