---
- hosts: '{{ host }}'
  connection: local
  
  vars:

  tasks:
    - name: Add A01-MM2PE-WEB01
      tower_host:
        name: A01-MM2PE-WEB01
        inventory: "AWS"
        state: present
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: "{{ tower_host }}"
        validate_certs: "{{ validate_certs }}"
        variables:
          name: "A01-MM2PE-WEB01"
          resource_group: "A01-MM2PE-RG"
