---
- hosts: '{{ host }}'
  connection: local

  tasks:
    - name: Create 0-include-2
      tower_job_template:
        name: "0-include-2"
        job_type: "run"
        inventory: "AWS"
        project: "ansible-juniper"
        playbook: "0-deploy-sg.yml"
        credential: "AWS-NET"
        state: "present"
        tower_username: "admin"
        tower_password: "admin"
        tower_host: "https://192.168.1.235"
        validate_certs: no
        credential: null
        extra_vars:
          - host: ''
