---
- hosts: '{{ host }}'
  connection: local

  tasks:
    - name: Update Security Group
      script: ./aws-security-group.py '{{ region }}' '{{ item.name }}' '{{ host }}' '{{ aws_access_key }}' '{{ aws_secret_key }}' '{{ item.description }}' '{{ vpc_id }}'
      when: item.present == true
      with_items:
        - "{{ security_groups }}"
