---
- hosts: '{{ host }}'
  connection: local
  
  vars:
    tower_username: "admin"
    tower_password: "admin"
    tower_host: "https://192.168.1.235"  

  tasks:
    - name: Add A01-MM2PE-WEB01
      tower_host:
        name: A01-MM2PE-WEB01
        inventory: "AWS"
        state: present
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: "{{ tower_host }}"
        validate_certs: no
        variables:
          name: "A01-MM2PE-WEB01"
          resource_group: "A01-MM2PE-RG"
