---
- hosts: '{{ host }}'
  connection: local
  
  vars:
    subscription_id: "11111-11111-11111-11111"
    resource_group: "A01-MM2PE-RG"
    inventory: "AWS"
    


  tasks:
    - name: Add {{ host_name }}
      tower_host:
        name: "{{ host_name }}"
        inventory: "{{ inventory }}"
        state: present
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: "{{ tower_host }}"
        validate_certs: "{{ validate_certs }}"
        variables:
          name: "{{ host_name }}"
          resource_group: "{{ resource_group }}"
          region: "east-us"
          resource_id: "/subscriptions/{{subscription_id}}/resourceGroups/{{ resource_group }}/providers/Microsoft.Web/sites/{{ site_name }}"
          firewall_cidrs:
            current_cidrs: True
            proposed_cidrs: True
            staging_cidrs: True
            subway_cidrs: True
          origin_url: "{{ origin_url }}"
          akamai_url: "{{ akamai_url }}"
      vars:
        site_name: "a01-mm2pe-web01"
        host_name: "A01-MM2PE-WEB01"
        origin_url: null
        akamai_url: null    
        
    - name: Add tower group
      tower_group:
        name: "{{ resource_group }}"
        description: "Azure Resource Group {{ resource_group }}"
        inventory: "{{ inventory }}"
        state: present
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: "{{ tower_host }}"
        validate_certs: "{{ validate_certs }}"
        source: manual
        instance_filters: A01-MM2PE-WEB01

