---
- hosts: '{{ host }}'
  connection: local

  tasks:
    - name: Add A01-MM2PE-WEB01
      tower_host:
        name: A01-MM2PE-WEB01
        description: 
        inventory: "AWS"
        state: present
        tower_username: "admin"
        tower_password: "admin"
        tower_host: "https://192.168.1.235"
        validate_certs: no
        variables:
           name: "A01-MM2PE-WEB01"
           resource_group: "A01-MM2PE-RG"
           region: "east-us"
           resource_id: "/subscriptions/1c99c59c-3db8-4b65-974d-c235a613073a/resourceGroups/A01-MM2PE-RG/providers/Microsoft.Web/sites/a01-mm2pe-web01"
           current_cidrs: True
           proposed_cidrs: True
           staging_cidrs: True
           subway_cidrs: True
