---
- hosts: '{{ host }}'
  connection: local
  
  vars:
    subscription_id: "11111-11111-11111-11111"

  tasks:
    - name: Add A01-MM2PE-WEB01
      tower_host:
        name: A01-MM2PE-WEB01
        inventory: "AWS"
        state: present
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: "{{ tower_host }}"
        validate_certs: "{{ validate_certs }}"
        variables:
          name: "A01-MM2PE-WEB01"
          resource_group: "{{ item.0 }}"
          region: "east-us"
          resource_id: "/subscriptions/{{subscription_id}}/resourceGroups/{{ item.0 }}/providers/Microsoft.Web/sites/{{ item.1 }}"
          current_cidrs: True
          proposed_cidrs: True
          staging_cidrs: True
          subway_cidrs: True
      with_items:
        "A01-MM2PE-RG"
        "a01-mm2pe-web01"
        
        
