---
- hosts: '{{ host }}'
  connection: local
  gather_facts: False


  roles:
    - role: paloaltonetworks.paloaltonetworks
    
  tasks:
      
    - name: Create a new cgw  
      ec2_customer_gateway:
        bgp_asn: '{{ item.bgp_asn }}'
        ip_address: '{{ item.untrust_ip }}'
        aws_secret_key: '{{ aws_secret_key }}'
        aws_access_key: '{{ aws_access_key }}'        
        name: "{{ item.hostname }}-CGW"
        region: '{{ region }}'
      register: cgw
      with_items:
        - "{{ hostvars[transit_fw] }}"   

    - name: create a VPN connection
      ec2_vpc_vpn:
        region: '{{ region }}'
        aws_secret_key: '{{ aws_secret_key }}'
        aws_access_key: '{{ aws_access_key }}'      
        state: present
        customer_gateway_id: '{{ cgw.results[0].gateway.customer_gateways[0].customer_gateway_id }}'
        vpn_gateway_id: '{{ vgw_id }}'
        tunnel_options:
          - TunnelInsideCidr: '{{ TunnelInsideCidr0 }}'
          - TunnelInsideCidr: '{{ TunnelInsideCidr1 }}'
      register: customer_gateway_configuration

    - name: Parse XML for AWS IPs
      xml:
        xmlstring: '{{ customer_gateway_configuration.customer_gateway_configuration }}'
        content: "text"
        xpath: "/vpn_connection/ipsec_tunnel/vpn_gateway/tunnel_outside_address/ip_address"
      register: tunnel_outside_address
      
    - name: Parse XML for Palo Tunnel IPs
      xml:
        xmlstring: '{{ customer_gateway_configuration.customer_gateway_configuration }}'
        content: "text"
        xpath: "/vpn_connection/ipsec_tunnel/customer_gateway/tunnel_inside_address/ip_address"
      register: tunnel_inside_address

    - name: Parse XML for AWS Tunnel IPs
      xml:
        xmlstring: '{{ customer_gateway_configuration.customer_gateway_configuration }}'
        content: "text"
        xpath: "/vpn_connection/ipsec_tunnel/vpn_gateway/tunnel_inside_address/ip_address"
      register: aws_tunnel_inside_address

    - name: Parse XML for tunnel PSKs
      xml:
        xmlstring: '{{ customer_gateway_configuration.customer_gateway_configuration }}'
        content: "text"
        xpath: "/vpn_connection/ipsec_tunnel/ike/pre_shared_key"
      register: pre_shared_key  
      
    - name: Add IKE gateway config to the firewall
      panos_ike_gateway:
        username: '{{ username }}'
        password: '{{ password }}'
        ip_address: '{{ item.panorama }}'
        template: '{{ item.template }}'
        state: 'present' 
        name: 'IKE-GATE-{{ host }}-{{ item.availability_zones[0] }}'
        version: 'ikev2'
        interface: '{{ item.untrust }}'
        enable_passive_mode: 'no'
        peer_ip_value: '{{ tunnel_outside_address.matches[0].ip_address }}'
        pre_shared_key: '{{ pre_shared_key.matches[0].pre_shared_key }}'
        ikev2_crypto_profile: 'ICP-DH_G2-AUTH_SHA256-EN_AES256'
        commit: False 
      with_items:
        - "{{ hostvars[transit_fw] }}"

    - name: Creat VPC Security Zone
      panos_zone:
        username: '{{ username }}'
        password: '{{ password }}'
        ip_address: '{{ item.panorama }}'
        template: '{{ item.template }}'  
        zone: '{{ host }}'
        mode: 'layer3'
      with_items:
        - "{{ hostvars[transit_fw] }}"
    
    - name: Create tunnel IP interfaces
      panos_tunnel:
        username: '{{ username }}'
        password: '{{ password }}'
        ip_address: '{{ item.panorama }}'
        template: '{{ item.template }}'
        if_name: "tunnel.1"
        ip: ['{{ tunnel_inside_address.matches[0].ip_address }}/30']
        vr_name: '{{ item.routing_instance }}'
        zone_name: "{{ host }}"
        commit: False
      with_items:
        - "{{ hostvars[transit_fw] }}"
      
    - name: Create IPSec Tunnel
      panos_ipsec_tunnel:
        username: '{{ username }}'
        password: '{{ password }}'
        ip_address: '{{ item.panorama }}'
        template: '{{ item.template }}'
        name: 'IPSSEC-TUN-{{ host }}-{{ item.availability_zones[0] }}'
        tunnel_interface: 'tunnel.1'
        ak_ike_gateway: 'IKE-GATE-{{ host }}-{{ item.availability_zones[0] }}'
        ak_ipsec_crypto_profile: 'IPCP-EN-AES256_AU-AES256_DH_G2'
        state: 'present'
        commit: False   
      with_items:
        - "{{ hostvars[transit_fw] }}"
