---
- hosts: '{{ host }}'
  connection: local
  tasks:
  
    - name: Create a new unattached vgw
      ec2_vpc_vgw:
        state: present
        region: '{{ region }}'
        aws_secret_key: '{{ aws_secret_key }}'
        aws_access_key: '{{ aws_access_key }}'
        name: "{{ host }}-VGW"
        type: ipsec.1
      register: vgw
      
    - name: Create a new cgw  
      ec2_customer_gateway:
        bgp_asn: 12345
        ip_address: 1.2.3.4
        aws_secret_key: '{{ aws_secret_key }}'
        aws_access_key: '{{ aws_access_key }}'        
        name: "{{ host }}-CGW"
        region: '{{ region }}'
      register: cgw

    - name: create a VPN connection
      ec2_vpc_vpn:
        region: '{{ region }}'
        aws_secret_key: '{{ aws_secret_key }}'
        aws_access_key: '{{ aws_access_key }}'      
        state: present
        customer_gateway_id: '{{ cgw.gateway.customer_gateways[0].customer_gateway_id }}'
        vpn_gateway_id: '{{ vgw.vgw.id }}'
        tunnel_options:
          - TunnelInsideCidr: '{{ TunnelInsideCidr0 }}'
          - TunnelInsideCidr: '{{ TunnelInsideCidr1 }}'
      register: customer_gateway_configuration

    - debug:
        var: customer_gateway_configuration

    - name: Parse XML for IPSec tunnel IPs.
      xml:
        xmlstring: "'{{ customer_gateway_configuration.customer_gateway_configuration }}'"
        content: "text"
        xpath: "/vpn_connection/ipsec_tunnel/customer_gateway/tunnel_inside_address/ip_address"

    - name: Parse XML for AWS IPs
      xml:
        xmlstring: '{{ customer_gateway_configuration }}'
        content: "text"
        xpath: "/vpn_connection/ipsec_tunnel/vpn_gateway/tunnel_outside_address/ip_address"
        
    - name: Parse XML for tunnel PSKs
      xml:
        xmlstring: '{{ customer_gateway_configuration }}'
        content: "text"
        xpath: "/vpn_connection/ipsec_tunnel/ike/pre_shared_key"
        

