- name: Apply configuration
  hosts: '{{ host }}'
  gather_facts: true
  connection: local
  
  tasks:
    - name: Distribution Switch uplinks to access switches
      junos_config:
        lines:         
          - set interfaces {{ item.0.{{ item.1.name }}.interface }} description "{{ item.1.name }}"
          - set interfaces {{ item.0.{{ item.1.name }}.interface }} vlan-tagging
          - set interfaces {{ item.0.{{ item.1.name }}.interface }} unit {{ item.1.id }} vlan-id {{ item.1.id }}
          - set interfaces {{ item.0.{{ item.1.name }}.interface }} unit {{ item.1.id }}  family inet address {{ item.0.{{ item.1.name }}.ip }}
          - set routing-instances vr-trust_{{ item.1.name }} interface {{ item.0.interface }}.{{ item.0.id }}
          - set routing-instances vr-trust_{{ item.1.name }} protocols ospf area 0.0.0.0 interface {{ item.0.{{ item.1.name }}.interface }}.{{ item.1.id }} passive
          - set routing-instances vr-trust_{{ item.1.name }} protocols ospf area 0.0.0.0 interface {{ item.0.{{ item.1.name }}.interface }}.{{ item.1.id }} hello-interval 1
          - set routing-instances vr-trust_{{ item.1.name }} protocols ospf area 0.0.0.0 interface {{ item.0.{{ item.1.name }}.interface }}.{{ item.1.id }} dead-interval 4
          - set routing-instances vr-trust_{{ item.1.name }} protocols ospf area 0.0.0.0 interface {{ item.0.{{ item.1.name }}.interface }}.{{ item.1.id }} authentication md5 1 key {{ ospf_md5 }}
          - set vlans {{ item.0.name }} vlan-id {{item.0.id }} 
          - set vlans access l3-interface {{ item.0.{{ item.1.name }}.interface }}.{{item.1.id }}    
        comment: "Push from Ansible"
        timeout: 25
        confirm: 3
      with_nested: 
        - '{{ access_config }}' 
        - '{{ vrfs }}'
        
      tags:
        - asw 

    - name: Wait to confirm no communication loss
      pause:
        seconds: 10
      tags:
        - asw  

    - name: Commit Configuration
      junos_config:
        confirm_commit: true
      tags:
        - asw 
