---
- hosts: '{{ host }}'
  connection: local
  tasks:
  
    - name: Create a new unattached vgw
      ec2_vpc_vgw:
        state: present
        region: '{{ region }}'
        aws_secret_key: '{{ aws_secret_key }}'
        aws_access_key: '{{ aws_access_key }}'
        name: "{{ host }}-VGW"
        type: ipsec.1
      register: created_vgw
      
    - name: Create a new cgw  
      ec2_customer_gateway:
        bgp_asn: 12345
        ip_address: 1.2.3.4
        aws_secret_key: '{{ aws_secret_key }}'
        aws_access_key: '{{ aws_access_key }}'        
        name: "{{ host }}-CGW"
        region: '{{ region }}'
      register: cgw

    - name: create a VPN connection
      ec2_vpc_vpn:
        state: present
        aws_secret_key: '{{ aws_secret_key }}'
        aws_access_key: '{{ aws_access_key }}'        
        region: '{{ region }}'
        vpn_gateway_id: "{{ created_vgw.id }}"
        customer_gateway_id: "{{ cgw.id }}"
