---
- hosts: '{{ host }}'
  connection: local

  tasks:
    - name: Create virtual network gateway with bgp
        azure_rm_virtualnetworkgateway:
          client_id: '{{ client_id }}'
          secret: '{{ secret }}'
          subscription_id: '{{ subscription_id }}'
          tenant: '{{ tenant }}'
          resource_group: VNET-RG
          name: myVirtualNetworkGateway
          sku: vpn_gw1
          ip_configurations:
            - name: testipconfig
              private_ip_allocation_method: Dynamic
              public_ip_address_name: testipaddr
          enable_bgp: yes
          virtual_network: A99
          bgp_settings:
            asn: 65515
            bgp_peering_address: "169.254.54.209"
