---
- hosts: '{{ host }}'
  connection: local
  tasks:
  
    - name: Create a new unattached vgw
      ec2_vpc_vgw:
        state: present
        region: '{{ region }}'
        aws_secret_key: '{{ aws_secret_key }}'
        aws_access_key: '{{ aws_access_key }}'
        name: '{{ vgw-name }}'
        type: ipsec.1
      register: created_vgw
