---
- hosts: '{{ host }}'
  connection: local
  gather_facts: False
    
  tasks:
      
    - name: Create a new cgw  
      ec2_customer_gateway:
        bgp_asn: '{{ item.bgp_asn }}'
        ip_address: '{{ item.untrust_ip }}'
        aws_secret_key: '{{ aws_secret_key }}'
        aws_access_key: '{{ aws_access_key }}'        
        name: "{{ item.hostnmae }}-CGW"
        region: '{{ region }}'
      register: cgw
      with_items:
        - "{{ hostvars[transit_fw] }}"   
