- name: Apply configuration
  hosts: '{{ host }}'
  gather_facts: true
  connection: local
  
  tasks:
    - name: Distribution Switch uplinks to access switches
      junos_config:
        lines:         
          - set interfaces {{ item.0.access.interface }} description "{{ item.1 }}"
        comment: "Push from Ansible"
        timeout: 25
        confirm: 3
      with_nested: 
        - '{{ access_config }}' 
        - '{{ vrfs }}'
        
      tags:
        - asw 

    - name: Wait to confirm no communication loss
      pause:
        seconds: 10
      tags:
        - asw  

    - name: Commit Configuration
      junos_config:
        confirm_commit: true
      tags:
        - asw 
