---
- name: Deploy a new VRF to Access VSys
  hosts: access_fabric
  connection: local
  gather_facts: no
  
  tasks: 
    - name: Configure CSW1
      import_playbook: CSW1-deploy.yaml
    
    - name: Configure CSW2
      import_playbook: CSW2-deploy.yaml    
    
