- name: Apply configuration
  hosts: '{{ host }}'
  gather_facts: true
  connection: local
  
  tasks:
    - name: Core Switch inet0 uplinks to palo altos
      junos_config:
        lines:         
          - set interfaces interface-range mfd325-mdf-fw1-ethernet-{{ item.0.palo_interface}}-range member {{ item.0.physical_fw1_1 }}
        comment: "Push from Ansible"
        timeout: 25
        confirm: 3
      when: '"item.1.present" == "true"
      with_nested: 
        - '{{ palo_alto_neighbors }}' 
        - '{{ vrfs }}'
      tags:
        - pa_uplinks  
