- hosts: localhost
  gather_facts: no
  
  vars:
    transit_fw: 'AWS_USE1_TRANS_FW1'
    
  tasks: 
    - name: print value_to_reuse
      debug:
        var: item
      with_items:
        - "{{ vault_credential }}"



