- hosts: localhost
  gather_facts: no
  tasks:
  
    - name: print value_to_reuse
      debug:
         vars: '{{ item }}'
      with_items: 
        - hostvars[inventory_hostname].AWS-USE1-TANS-FW1


