- hosts: localhost
  gather_facts: no
  
  vars:
    transit_fw: "AWS-USE1-TRANS-FW1"
  tasks:
  
    - name: print value_to_reuse
      debug:
        var: item
      with_items:
        - "{{ hostvars[groups['AWS-DEV'][AWS-USE1-TRANS-FW1']] }}"


