- hosts: localhost
  gather_facts: no
  
  vars:
    transit_fw: 'AWS_USE1_TRANS_FW1'

  
    - name: print value_to_reuse
      debug:
        var: item
      with_items:
        - "{{ hostvars[transit_fw]['template'] }}"



