- hosts: localhost
  gather_facts: no
  tasks:
  
    - name: print value_to_reuse
      debug:
         vars: '{{ item }}'
      with_items: 
        - "{{ hostvars[groups['AWS-DEV'][0]].'AWS-USE1-TANS-FW1' }}"


