- hosts: localhost
  gather_facts: no
  tasks:
  
    - name: print value_to_reuse
      debug:
         vars: '{{ item }}'
      with_items: 
        - "{{ groups['AWS-DEV']hosts['AWS-USE1-TANS-FW1'] }}"

