- hosts: localhost
  gather_facts: no
  
  vars:
    transit_fw: "AWS-USE1-TRANS-FW1"
  tasks:
  
    - name: print value_to_reuse
      add_host:
        hostname: AWS_USE1_TRANS_FW1
      debug:
        var: '{{ panorama }}'



