---
- name: Get device facts and configuration
  hosts: MFD325-CSW1
  roles:
    - juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Retrieve device facts and configuration and save facts to file
      juniper_junos_facts:        
        savedir: "/tmp/"
        config_format: "xml"
      register: result

    - name: Print configuration
      debug:
        var: result.ansible_facts.junos.config
