---
- name: Configure Juniper Access Switch
  hosts: MFD325-CSW1
  connection: local
  gather_facts: no
  roles:
    - juniper.junos
    
  vars:
  
    - build_dir: '/tmp/'

    - csw1_vars:
        - irb_net_oct: "{{ irb_net_oct }}"
          irb_prefix: "{{ irb_prefix }}"
          vlan_id: "{{ vlan_id }}"
          role: "{{ role }}"
          xe-0/0/12_octet: "{{ xe-0/0/12_octet }}"
          xe-0/0/12_prefix: "{{ xe-0/0/12_prefix }}"
  
  tasks:

    - name: Build JunOS System config
      template: src=irb.set.j2 dest={{build_dir}}/irb.set
      with_items: csw1_vars


    - name: Apply System config
      junos_install_config: host={{ inventory_hostname }} file={{ build_dir }}irb.set overwrite=no timeout=300
