---
- name: Configure Juniper Access Switch
  hosts: MFD325-CSW1
  connection: local
  gather_facts: no
  roles:
    - juniper.junos
    
  vars:
  
    - build_dir: '/tmp/'
  
    - irb_prefix: "{{ hostvars[interface]['irb_prefix'] }}"
    - irb_net_oct: "{{ hostvars[interface]['irb_net_oct'] }}"

    - switch_vars:
        - irb_net_oct: "{{ hostvars[interface]['irb_net_oct'] }}"
          irb_prefix: "{{ hostvars[interface]['irb_prefix'] }}"
          vlan_id: "{{ vlan_id }}"
          role: "{{ role }}"


  tasks:

    - name: Build JunOS System config
      template: src=irb.set.j2 dest={{build_dir}}/irb.set
      with_items: switch_vars


    - name: Apply System config
      junos_install_config: host={{ inventory_hostname }} file={{ build_dir }}irb.set overwrite=no timeout=300
