- name: Apply configuration
  hosts: MFD325-MDF-CSW1
  gather_facts: False
  tasks:
    - name: Juniper Commit
      junos_config:
        lines:
          - set system host-name AMS4-LAB-MX80-01
        #src_format: set
        comment: "Push from Ansible"
