- name: Apply configuration
  hosts: MFD325-MDF-CSW1
  gather_facts: True
  connection: local
  tasks:
    - name: Juniper Commit
      junos_config:
        lines:
          - set system host-name "{{ hostname }}"
        timeout: 30
        comment: "Push from Ansible"
