---
- name: Configure Juniper Access Switch
  hosts: access_fabric
  connection: local
  gather_facts: no
  roles:
    - juniper.junos
    - paloaltonetworks.paloaltonetworks
    
  vars:
  
    - build_dir: '/tmp/'
      config_file: 'irb.set'

    - csw_vars:
        - irb_net_oct: "{{ irb_net_oct }}"
          irb_prefix: "{{ irb_prefix }}"
          vlan_id: "{{ vlan_id }}"
          role: "{{ role }}"
          ospf_md5: "{{ ospf_md5 }}"
          ge_0_0_2_octet: "{{ ge_0_0_2_octet }}"
          ge_0_0_2_prefix: "{{ ge_0_0_2_prefix }}"
          ge_0_0_3_octet: "{{ ge_0_0_3_octet }}"
          ge_0_0_3_prefix: "{{ ge_0_0_3_prefix }}"

  hosts: MFD325-MDF-FW1_ACCESS_VSYS
  tasks:

    - name: Create Palo Alto Template Network Configuration
      script: palo-fabric.py {{ palo_username }} '{{ palo_password }}' {{ vlan_id }} {{ eth1_1_prefix }} {{ eth1_1_octet }} {{ eth1_2_prefix }} {{ eth1_2_octet }} {{ pa_template }} {{ virtual_router }} {{ vsys_name }} {{ zone_name }} 

  
