---
- name: Configure Juniper Access Switch
  hosts: core_switches
  connection: local
  gather_facts: no
  roles:
    - juniper.junos
    
  vars:
  
    - build_dir: '/tmp/'
      config_file: 'irb.set'


  tasks:
           
    - name: Set VLAN access and trunking
      junos_config:
      lines:
        - set system host-name hostvars[host]groups['core_switches']
  
    - name: confirm a previous commit
      junos_config:
        confirm_commit: yes
