---
- name: Configure Juniper Access Switch
  hosts: MFD325-CSW1
  connection: local
  gather_facts: no
  roles:
    - juniper.junos
    
  vars:
  
    - build_dir: '/tmp/'
      config_file: 'irb.set'

    - csw1_vars:
        - irb_net_oct: "{{ irb_net_oct }}"
          irb_prefix: "{{ irb_prefix }}"
          vlan_id: "{{ vlan_id }}"
          role: "{{ role }}"
          ospf_md5: "{{ ospf_md5 }}"
          xe_0_0_12_octet: "{{ xe_0_0_12_octet }}"
          xe_0_0_12_prefix: "{{ xe_0_0_12_prefix }}"
          xe_0_0_13_octet: "{{ xe_0_0_13_octet }}"
          xe_0_0_13_prefix: "{{ xe_0_0_13_prefix }}"
          
  tasks:

    - name: Build JunOS System config
      template: src=irb.set.j2 dest={{build_dir}}/irb.set
      with_items: csw1_vars


    - name: Apply System config
      juniper_junos_config:
        load: 'merge'
        file: "{{ build_dir }}{{ config_file }}"
        host: "{{ inventory_hostname }}"
        confirm: 3
        check_commit_wait: 60
        
    - name: Apply System config
      juniper_junos_config:
        commit_empty_changes: true
        
