---
- name: Configure Juniper Access Switch
  hosts: MFD325-MDF-CSW1
  connection: local
  gather_facts: no
  roles:
    - juniper.junos
    
  vars:
  
    - build_dir: '/tmp/'
      config_file: 'irb.set'


  tasks:
           
    - name: Build Core Switch Configuration	
      template: src=description.set.j2 dest={{build_dir}}/MFD325-MDF-CSW1.set	
      with_items: "{{ hostvars }}"

    - name: Apply Core Switch Configuration	
      juniper_junos_config:	
        load: 'merge'	
        file: "{{ build_dir }}/MFD325-MDF-CSW1.set"
        confirm: 3	
        check_commit_wait: 3	

    - name: Wait to confirm no communication loss	
      pause:	
        seconds: 10	


    - name: Commit Configuration	
      juniper_junos_config:	
        commit_empty_changes: true  

  
