- name: Apply configuration
  hosts: core_switches
  gather_facts: False
  tasks:
    - name: Juniper Commit
      junos_config:
        lines:
          - set system host-name AMS4-LAB-MX80-01
        src_format: set
        comment: "Push from Ansible"
        provider:
          timeout: 60
