- name: Apply configuration
  hosts: core_switches
  gather_facts: True
  connection: local
  tasks:
    - name: Juniper Commit
      junos_config:
        lines:
          - set system host-name "{{ hostname }}"
        timeout: 30
        comment: "Push from Ansible"
        confirm: 3

    - name: Wait to confirm no communication loss	
      pause:	
        seconds: 10	

    - name: Commit Configuration	
      junos_config:	
        confirm_commit: true  
