---
- name: Configure Juniper Access Switch
  hosts: access_fabric
  connection: local
  gather_facts: no
  roles:
    - juniper.junos
    - paloaltonetworks.paloaltonetworks
    
  vars:
  
    - build_dir: '/tmp/'
      config_file: 'irb.set'

    - csw1_vars:
        - irb_net_oct: "{{ irb_net_oct }}"
          irb_prefix: "{{ irb_prefix }}"
          vlan_id: "{{ vlan_id }}"
          role: "{{ role }}"
          ospf_md5: "{{ ospf_md5 }}"
          xe_0_0_12_octet: "{{ xe_0_0_12_octet }}"
          xe_0_0_12_prefix: "{{ xe_0_0_12_prefix }}"
          xe_0_0_13_octet: "{{ xe_0_0_13_octet }}"
          xe_0_0_13_prefix: "{{ xe_0_0_13_prefix }}"
          
  tasks:
    - hosts: DBY289-LAB-FW1
    - name: Create VPC VPN and Panorama Config
      script: palo-fabric.py {{ palo_username }} '{{ palo_password }}' {{ vlan_id }} {{ eth1_23_prefix }} {{ eth1_23_octet }} {{ pa_template }} {{ virtual_router }} {{ vsys_name }} {{ zone_name }} 

    - hosts: MFD325-CSW1
    - name: Build JunOS System config
      template: src=irb.set.j2 dest={{build_dir}}/irb.set
      with_items: csw1_vars

    - hosts: MFD325-CSW1
    - name: Apply System config
      juniper_junos_config:
        load: 'merge'
        file: "{{ build_dir }}{{ config_file }}"
        host: "{{ inventory_hostname }}"
        confirm: 3
        check_commit_wait: 3

    - name: Pause
      pause:
        minutes: 1

    - hosts: MFD325-CSW1
    - name: Apply System config
      juniper_junos_config:
        commit_empty_changes: true
        
