---
- name: Apply configuration
  hosts: '{{ host }}'
  gather_facts: true
  connection: local

  tasks:

    - name: Palo Config
      script: scripts/campus-fabric.py {{ username }} '{{ password }}' {{ panorama }} {{ device_template }} {{ item.1.id }} {{ item.1.name }} {{ item.0.interface }} {{ item.0.vlan_prefix }} {{ item.0.host_bit }} {{ vsys_name }} {{ router_id }} {{ present }} {{ ospf_area }}
      with_nested: 
        - '{{ core_switches_neighbors }}' 
        - '{{ vrfs }}'
      tags: 
        - palo_config
