- hosts: DBY289-LAB-FW1
  connection: local

  roles:
    - role: paloaltonetworks.paloaltonetworks
    
  tasks:

    - name: Create VPC VPN and Panorama Config
      script: palo-fabric.py {{ palo_username }} '{{ palo_password }}' {{ vlan_id }} {{ eth1_23_prefix }} {{ eth1_23_octet }} {{ template }} {{ virtual_router }} {{ vsys_name }} {{ zone_name }} 
