---
- hosts: '{{ host }}'
  connection: local


  roles:
    - role: paloaltonetworks.paloaltonetworks
    
  tasks:
    - name: Create Static Route
      panos_static_route:
        ip_address: '{{ ip_address }}'
        username: '{{ username }}'
        password: '{{ password }}'
        template: '{{ device_template }}'
        name: '{{ route_name }}'
        destination: '{{ destination_cidr }}'
        nexthop: '{{ next_hop }}'
        virtual_router: '{{ virtual_router }}'
