- hosts: '{{ host }}'
  connection: local

  roles:
    - role: PaloAltoNetworks.paloaltonetworks
    
  tasks:
    - name: Create Static Route
      panos_static_route:
        ip_address: 192.168.1.1
        username: admin
        password: admin
        template: "MFD325-MDF-FW1"
        name: '{{ route_name }}'
        destination: '{{ destination_cidr }}'
        nexthop: '{{ next_hop }}'
        virtual_router: '{{ virtual_router }}'
