---
- hosts: '{{ host }}'
  connection: local


  roles:
    - role: paloaltonetworks.paloaltonetworks
    
  tasks:
    - name: Create Static Route
      panos_static_route:
        ip_address: '{{ ip_address }}'
        username: '{{ username }}'
        password: '{{ password }}'
        template: '{{ device_template }}'
        virtual_router: '{{ item.virtual_router }}'
        name: '{{ item.name }}'
        destination: '{{ item.destination }}'
        interface: '{{ item.interface }}'
        nexthop_type: '{{ item.nexthop_type }}'
      with_items:
        - '{{ static_routes }}'     
      tags:
        - static

    - name: Create Redistribution Profile
      panos_redistribution:
        ip_address: '{{ ip_address }}'
        username: '{{ username }}'
        password: '{{ password }}'
        template: '{{ device_template }}'
        vr_name: '{{ item.virtual_router }}'
        name: '{{ item.name }}'
        filter_destination: '{{ item.filter_destination }}'
        action: '{{ item.action }}'
        filter_type: '{{ item.filter_type }}'
        priority: '{{ item.priority }}'        
      with_items:
        - '{{ redistribution_profile }}'     
      tags:
        - redistribution
