---
- hosts: '{{ host }}'
  connection: local


  roles:
    - role: paloaltonetworks.paloaltonetworks
    
  tasks:
    - name: Create Static Route
      panos_static_route:
        ip_address: '{{ ip_address }}'
        username: '{{ username }}'
        password: '{{ password }}'
        template: '{{ device_template }}'
        virtual_router: '{{ item.virtual_router }}'
        name: '{{ item.name }}'
        destination: '{{ item.destination }}'
        interface: '{{ item.interface }}'
        nexthop_type: '{{ item.nexthop_type }}'
      with_items:
        - '{{ static_routes }}'        
