---
- name: Apply configuration
  hosts: '{{ host }}'
  gather_facts: true
  connection: local

  tasks:

    - name: Palo Config
      script: test1.py 
      register: py_return

    - name: Debug variables
      debug:
        var: py_return.stdout_lines[0]
